# How often to reset players last rest time
# You should only change this if you have a different daylight cycle speed than the default
check-interval: 600 # seconds

# A list of worlds where the plugin won't be enabled
worlds-blacklist:
  list:
    - "disable_plugin1"
    - "disable_plugin2"

  # If true, the list of worlds above will act as a whitelist, meaning only those worlds will have the plugin enabled
  act-as-whitelist: false
