name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${mainPackage}.${name}
version: ${version}
api-version: 1.13
folia-supported: true

softdepend:
  - PlaceholderAPI

commands:
  nophantoms:
    description: Main command for Personal Phantoms
    aliases:
      - phantoms
    permission: pp.nophantoms

permissions:
  pp.reload:
    description: Allows the player to use /nophantoms reload
  pp.nophantoms:
    description: Allows the player to use /nophantoms
    default: true
  pp.nophantoms.others:
    description: Allows the player to toggle phantoms for other players
  pp.nophantoms.bypass:
    description: Allows the player to bypass the /nophantoms command cooldown
  pp.nophantoms.cooldown.#:
    description: "Set a custom cooldown for the /nophantoms command, replace # with the cooldown time (in seconds)"
    default: false
